version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SKIP_OWNER_SETUP=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=America/Bogota
      - NODES_BARE_LIST=n8n-nodes-langchain
    volumes:
      - ./n8n:/home/node/.n8n
      - ./modelo_conocimiento:/home/node/.n8n/modelo_conocimiento
    user: "0:0"
    # Esto fuerza que host.docker.internal apunte al host mediante host-gateway (recomendado)
    extra_hosts:
      - "host.docker.internal:host-gateway"
